<?php

namespace site\TournoiBundle\Entity;

/**
 * ButeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ButeurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPublishedQueryBuilder() {
        return $this
            ->createQueryBuilder('b')
            ;
    }
}
