<?php

namespace site\TournoiBundle\Entity;

/**
 * MatchTournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchTournoiRepository extends \Doctrine\ORM\EntityRepository
{
}
