<?php

namespace site\TournoiBundle\Entity;

/**
 * MatchTournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchTournoiRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMatchsWithUsers($tournoi)
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->join('m.userDom', 'userDom')
            ->addSelect('userDom')
            ->join('m.userExt', 'userExt')
            ->addSelect('userExt')
            ->where('m.tournoi = :tournoi')
            ->setParameter('tournoi',$tournoi)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
