<?php

namespace site\TournoiBundle\Entity;

/**
 * MatchTournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchTournoiRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMatchsWithUsersAndEquipes($tournoi)
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->join('m.userDom', 'userDom')
            ->join('m.userExt', 'userExt')
            ->join('m.equipeDom', 'equipeDom')
            ->join('m.equipeExt', 'equipeExt')
            ->addSelect('userDom')
            ->addSelect('userExt')
            ->addSelect('equipeDom')
            ->addSelect('equipeExt')
            ->where('m.tournoi = :tournoi')
            ->setParameter('tournoi',$tournoi)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function getLastScoreMatch($tournoi)
    {
        $query = $this
            ->createQueryBuilder('m')
            ->where('m.tournoi = :tournoi')
            ->setParameter('tournoi',$tournoi)
            ->orderBy('m.dateScore','DESC')
            ->setMaxResults(1)
            ->getQuery()
        ;

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
