<?php

namespace site\TournoiBundle\Entity;

/**
 * TournoiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiUserRepository extends \Doctrine\ORM\EntityRepository
{
}
