<?php

namespace site\TournoiBundle\Entity;

/**
 * TournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMatchsWithUsers(){
        $qb = $this
            ->createQueryBuilder('t')
            ->join('t.matchs', 'matchs')
            ->addSelect('matchs')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
