<?php

namespace site\TournoiBundle\Entity;

/**
 * TournoiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournoiRepository extends \Doctrine\ORM\EntityRepository
{
}
