<?php

namespace site\TournoiBundle\Entity;

/**
 * VersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VersionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAllVersionOrderedByDate()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM siteTournoiBundle:Version v ORDER BY date_depart DESC'
            )
            ->getResult();
    }

    /**
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLatest()
    {
        $query = $this->createQueryBuilder('v')
            ->where('CURRENT_DATE() > v.date_start')
            ->orderBy('v.date_start','DESC')
            ->setMaxResults(1)
            ->getQuery();

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
