<?php

namespace site\FrontBundle\Entity;

/**
 * ChampionnatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionnatRepository extends \Doctrine\ORM\EntityRepository
{
}
